name: CI Pipeline - Music Analysis ML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3️⃣ Install system dependencies (for librosa)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libsndfile1

    # 4️⃣ Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 5️⃣ Lint check (basic)
    - name: Python syntax check
      run: |
        python -m compileall src streamlit_app.py

    # 6️⃣ Run unit tests
    - name: Run tests
      run: |
        pytest tests/

    # 7️⃣ Import test (Streamlit + Librosa)
    - name: Import sanity check
      run: |
        python - <<EOF
        import librosa
        import streamlit
        print("Imports successful")
        EOF

    # 8️⃣ Docker build check
    - name: Build Docker image
      run: |
        docker build -t music-analysis-ml .
